name = "snacklab"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[[kv_namespaces]]
binding = "STORE_KV"
id = "41c514b338d742ae9acb06c89fb3a3a6"

[[r2_buckets]]
binding = "STORE_R2"
bucket_name = "snacklab-uploads"

# Set ADMIN_PASSWORD with `wrangler secret put ADMIN_PASSWORD`
